"""empty message

Revision ID: 00a9c6f676bb
Revises: 79cd0b8b7329
Create Date: 2023-04-11 12:56:47.826083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a9c6f676bb'
down_revision = '79cd0b8b7329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=120), nullable=False))
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    # ### end Alembic commands ###
