"""empty message

Revision ID: 149628812ea0
Revises: 3cd52c6cff72
Create Date: 2023-04-11 12:40:02.397694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149628812ea0'
down_revision = '3cd52c6cff72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characterFavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetsFavorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetsFavorite')
    op.drop_table('characterFavorite')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
