"""empty message

Revision ID: 79cd0b8b7329
Revises: 149628812ea0
Create Date: 2023-04-11 12:43:38.792293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cd0b8b7329'
down_revision = '149628812ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=120), nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
